#!/bin/sh -l
# FILENAME:  pic_run.sh

#SBATCH -A standby
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=4:00:00
#SBATCH --job-name myjobname
#SBATCH --array=0-79 

# Edit the last sbatch command by entering a number on the array which signifies 
# how many modes need to be run. If there is a list of 67 modes that need to be run
# the line should read --array=0-66. If you do not want to run them all at once you
# can run them in chunks e.g. 0-34 then 35-66.

# This file contains MANY refrences to specific directories each of these must
# be changed depending on the user using this and where files are stored for 
# that specific user. Tt also refrences running "straight_waveguide_recreate.ctl"
# which is the name of a specific meep ctl file. This must also be changed 
# according to which exact .ctl file needs to be run. All lines that must be
# edited will be marked with an edit comment.


echo "NUM_LINES received: $NUM_LINES"

source ~zhu797/.profile

# Print the hostname of the compute node on which this job is running.
/bin/hostname

# Change to the directory from which you originally submitted this job.
cd $SLURM_SUBMIT_DIR

# Read the k_z and freq from the file based on the task ID
param_line=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" params.txt) #Looking for params.txt generated by matlab txt_gen.m (make sure to name this params.txt)
params=($param_line)

# Extract k_z and freq
k_z=${params[0]}
freq=${params[1]}

# Create a temporary unique directory for this run
run_dir="run_${SLURM_ARRAY_TASK_ID}_kz_${k_z}_freq_${freq}"
mkdir -p $run_dir
cd $run_dir

cp /scratch/bell/rodri979/run_file_folder/straight_waveguide_recreate.ctl . # EDIT

# Run the meep command with the extracted parameters
mpirun -np 2 meep use_dir=false output_field=true freq=$freq df=0.01 k_z=$k_z straight_waveguide_recreate.ctl #EDIT

# Move output files to the appropriate k_z directory with unique filenames
cd /scratch/bell/rodri979/meep_files/matlab/odd_2_src_pics/ #EDIT
output_dir="kz_${k_z}"
mkdir -p $output_dir

cd /scratch/bell/rodri979/run_file_folder/ #EDIT
cd $run_dir

for file in straight_waveguide_recreate-denergy*.h5; do #EDIT
  mv "$file" "/scratch/bell/rodri979/meep_files/matlab/odd_2_src_pics/${output_dir}/${k_z}_freq_${freq}_pwr${file#straight_waveguide_recreate-denergy}"; #EDIT
done

# Clean up the temporary directory
rm straight_waveguide_recreate.ctl #EDIT
cd ..
rm -r $run_dir

echo "Done"
