function harminv_dat = load_harminv_dat(data, k_start, k_step)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   load_harminv_dat loads harminv data for multiple k values run in meep
%   data -> .dat file from harminv runs (generated by grepping a .out file
%           by filtering for "harminv")
%   k_start -> The lowest k value ran
%   k_step -> The k step size used
%   
%    Output format:
%
%
%    k_values    frequency    imag. frequency    Q    amp    error
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

harminv_dat = readtable(data);
harminv_dat(:,1) = [];
harminv_dat(:,5) = [];
harminv_dat = table2array(harminv_dat);
k = k_start;
k_list = zeros(numel(harminv_dat(:,1)),1);
nan_index = 1;

for index = linspace(1,numel(harminv_dat(:,1)),numel(harminv_dat(:,1)))
    k_list(index) = k; 
    if isnan(harminv_dat(index,2))
        k = k + k_step;
        nan_rows(nan_index) = index;
        nan_index = nan_index + 1;
    end
end

harminv_dat = [k_list harminv_dat];

for index = flip(nan_rows)
    harminv_dat(index,:) = [];
end

end
